### ISSUE TITLE
Finishing milestone 1.0.0 - Phase 2

### ISSUE THREAD

**Issue by Nachtfeuer** [thomas-lehmann-private/hyperion-task-processor#54]
- **Changing the version to release** - a pom.xml modification; it can be done without branch.
 - **Updating the github pages**
 - **Tagging the repository with release version** - it should trigger the related workflow that
   does also one build and finally publishing the artifacts on Github.

----
 **Finish**:
  - Announcing new version at [here](https://github.com/thomas-lehmann-private/hyperion/discussions/categories/announcements).
  - Also communicate that the next milestone is planned and already has stories.
  - Ask the community for interest in new features not yet in the milestone.
  - Closing the milestone 1.0.0

**Comment by Nachtfeuer** [comment]
Documentation now also fine: https://thomas-lehmann-private.github.io/hyperion-task-processor/

**Comment by Nachtfeuer** [comment]
Again removed the tag because the used release script (not my code) does not take both artifacts for any reason. I have to investigate to get the issue resolved by the author or to find another solution.

**Comment by Nachtfeuer** [comment]
Look like this might be an alternative: https://github.com/ncipollo/release-action

**Comment by Nachtfeuer** [comment]
Unbelieveable - the scripts are not capable to fetch two files as artifacts.

**Comment by Nachtfeuer** [comment]
Another try (on another day). I found following code:

```yaml
run: |
  gh release create ${{ env.VERSION }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" ${{ env.FILES }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "tag for release"
  MESSAGE: "message for release"
  NAME: "release name"
  FILES: path/to/file1 path/to/file2 ...
 ```
